#!/bin/sh
TARGET_LINK=/usr/local/MQJExplorer
TARGET_DIR=/usr/local/MQJExplorer-0.14

UnInstallAll() {
	rm -rf "$TARGET_DIR" 2>/dev/null 
	rm -f "$TARGET_LINK" 2>/dev/null
	rm -f /usr/local/bin/MQJExplorer 2>/dev/null
	rm -f /usr/share/applications/MQJExplorer.desktop 2>/dev/null
	rm -f /usr/share/desktop-directories/MQJExplorer.directory 2>/dev/null
	rm -f /usr/share/pixmaps/MQJExplorer.png 2>/dev/null
	update-menus
}

case "$1" in
    purge|remove|upgrade)
        UnInstallAll 
	exit 0
    ;;

    failed-upgrade|abort-install|abort-upgrade|disappear)
	exit 0
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
esac
