#!/bin/sh
TARGET_LINK=/usr/local/MQJExplorer
TARGET_DIR=/usr/local/MQJExplorer-0.14

installAll() {
    ln -s ${TARGET_DIR} ${TARGET_LINK}
    rm -f /usr/local/bin/MQJExplorer 2>/dev/null
    ln -s ${TARGET_LINK}/runme.sh /usr/bin/MQJExplorer 2>/dev/null
    
	cp "${TARGET_LINK}/xdg/MQJExplorer.desktop" "/usr/share/applications"
	cp "${TARGET_DIR}/xdg/MQJExplorer.directory" "/usr/share/desktop-directories"
	cp "${TARGET_LINK}/xdg/MQJExplorer.png" /usr/share/pixmaps
		
	update-menus	
}

case "$1" in
    configure)
	installAll 
	exit 0
    ;;

    configure)

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
